const assert = require('assert')
const { crownDirection, crownDebounceMs, keyDirection } = require('../utils/crown')

assert.strictEqual(crownDirection(36, 1, 36), 1, 'positive degree should move forward')
assert.strictEqual(crownDirection(36, -1, 36), -1, 'negative degree should move backward')
assert.strictEqual(crownDirection(36, 0, 36), 0, 'press event must not navigate')
assert.strictEqual(crownDirection(36, undefined, 36), 0, 'missing degree must not navigate')
assert.strictEqual(crownDirection(13, 10, 36), 0, 'non-crown key must not navigate')
assert.strictEqual(crownDebounceMs('gtr4'), 90)
assert.strictEqual(crownDebounceMs('active2'), 120)
assert.strictEqual(crownDebounceMs('balance'), 130)
assert.strictEqual(keyDirection(40, 38, 40), 1, 'down key should move forward')
assert.strictEqual(keyDirection(38, 38, 40), -1, 'up key should move backward')
assert.strictEqual(keyDirection(36, 38, 40), 0, 'unrelated key must pass through')
console.log('crown helper tests: passed')
